// Performance of the embedded painting (demo page). Writes docs/performance.md.
//
//   pnpm perf:embed
//
// For each profile and seed: time from navigation to the first painting being visible
// (mount().ready), the longest main-thread task while loading, and SVG elements on screen.
// Budgets come from PLAN.md Phase 6, set against the upstream baseline in docs/baseline.md.
import { writeFileSync } from "node:fs";
import { startServer } from "./lib/server.js";
import { launch } from "./lib/upstream.js";

const SEEDS = ["1", "42", "coast", "sydney", "1234567890123"];
const PROFILES = [
  { name: "desktop (1280 x 800)", viewport: { width: 1280, height: 800 }, throttle: 1 },
  { name: "phone (390 x 844), 4x CPU throttle", viewport: { width: 390, height: 844 }, throttle: 4 },
];
const BUDGET = { readyMs: 1500, longestTaskMs: 200, elements: 15000 };

const INIT = () => {
  window.__lt = [];
  new PerformanceObserver((l) => {
    for (const e of l.getEntries()) window.__lt.push(e.duration);
  }).observe({ type: "longtask", buffered: true });
};

const server = await startServer();
const browser = await launch();
const rows = {};
for (const prof of PROFILES) {
  rows[prof.name] = [];
  for (const seed of SEEDS) {
    const page = await browser.newPage({ viewport: prof.viewport });
    const cdp = await page.context().newCDPSession(page);
    await cdp.send("Emulation.setCPUThrottlingRate", { rate: prof.throttle });
    await page.addInitScript(INIT);
    await page.goto(`${server.url}demo/index.html?seed=${seed}&mode=static`);
    const r = await page.evaluate(async () => {
      await window.demo.scene.ready;
      const ready = performance.now();
      await new Promise((res) => setTimeout(res, 300));
      const svg = document.querySelector("#hero > div").shadowRoot.querySelector("svg");
      return { ready, longest: Math.max(0, ...window.__lt), elements: svg.querySelectorAll("*").length };
    });
    rows[prof.name].push({ seed, ...r });
    console.log(`${prof.name.padEnd(36)} ${seed.padEnd(14)} ready ${Math.round(r.ready)} ms, longest task ${Math.round(r.longest)} ms, ${r.elements} elements`);
    await page.close();
  }
}
const chromium = browser.version();
await browser.close();
await server.close();

const median = (xs) => {
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.floor(s.length / 2)];
};
const ok = (v, b) => (v <= b ? "within" : "**over**");
let md = `# Performance of the embedded painting

Generated by \`pnpm perf:embed\` (tools/perf-embed.js) on ${new Date().toISOString().slice(0, 10)}, Chromium ${chromium}, headless, on the same Windows 11 desktop machine as docs/baseline.md. The demo page mounts the coast in \`static\` mode (hero, height 220 to 420 px) plus a second 180 px painting.

- **ready**: navigation start to the hero painting being visible (\`mount().ready\`: first view and paper generated in the worker and inserted).
- **longest task**: longest main-thread task while loading. Generation runs in the worker, so this is mostly inserting markup.
- **elements**: SVG elements on screen in the hero.

Budgets (PLAN.md Phase 6, proposed against docs/baseline.md): ready within ${BUDGET.readyMs} ms on the throttled phone profile (upstream: about 2,800 ms throttled for its first screen), longest main-thread task under ${BUDGET.longestTaskMs} ms (upstream: 2,600 to 4,200 ms throttled), on-screen elements under ${BUDGET.elements.toLocaleString("en-AU")} (upstream: about 41,000).

`;
for (const prof of PROFILES) {
  const rs = rows[prof.name];
  md += `## ${prof.name}\n\n| seed | ready (ms) | longest task (ms) | elements |\n|---|---:|---:|---:|\n`;
  for (const r of rs) md += `| ${r.seed} | ${Math.round(r.ready)} | ${Math.round(r.longest)} | ${r.elements} |\n`;
  const mr = median(rs.map((r) => r.ready));
  const ml = median(rs.map((r) => r.longest));
  const me = median(rs.map((r) => r.elements));
  md += `| **median** | **${Math.round(mr)}** | **${Math.round(ml)}** | **${me}** |\n\n`;
  md += `Against budget: ready ${ok(mr, BUDGET.readyMs)}, longest task ${ok(ml, BUDGET.longestTaskMs)}, elements ${ok(me, BUDGET.elements)}.\n\n`;
}
md += `## Bundle size

\`pnpm build\` (Vite library mode, minified, gzip -9 measured on 3 October 2026): a page that uses \`<coast-inf>\` loads \`element.js\` (0.5 kB gzipped), the \`mount\` chunk (4.0 kB) and the worker (27.2 kB): about **32 kB gzipped**, against the plan's budget of about 60 kB. \`coast-inf.js\` (32 kB gzipped) also carries the generator for \`renderToSVG()\`; bundlers drop it when only \`mount\` is imported (\`sideEffects\` is set in package.json).
`;
writeFileSync(new URL("../docs/performance.md", import.meta.url), md);
console.log("wrote docs/performance.md");
