// Baseline performance of the upstream page. Writes docs/baseline.md.
//
//   pnpm perf
//
// Measured per seed, on desktop and with 4x CPU throttling (Chromium's
// Emulation.setCPUThrottlingRate through the DevTools protocol, as Lighthouse's mobile
// profile does; Playwright has no built-in CPU throttling):
//   svgInserted  ms from navigation start until the first <svg> is in the DOM. A
//                MutationObserver callback runs right after the inline script that calls
//                update(), so this is generation plus innerHTML.
//   fcp          first contentful paint.
//   load         the load event.
//   scrollStep   median ms for xcroll(200) plus the next frame (upstream rebuilds the whole
//                SVG on every scroll step).
//   elements     element count inside the on-screen <svg>.
//   bytes        length of the on-screen SVG markup (MEM.canv).
import { writeFileSync } from "node:fs";
import { SEEDS } from "./golden.js";
import { launch, UPSTREAM_URL } from "./lib/upstream.js";

const PROFILES = [
  { name: "desktop", throttle: 1 },
  { name: "mobile CPU (4x throttle)", throttle: 4 },
];
const SCROLL_STEPS = 5;

const INIT = () => {
  window.__perf = {};
  new MutationObserver((_, obs) => {
    if (document.getElementById("SVG")) {
      window.__perf.svgInserted = performance.now();
      obs.disconnect();
    }
  }).observe(document, { childList: true, subtree: true });
  new PerformanceObserver((list) => {
    for (const e of list.getEntries()) if (e.name === "first-contentful-paint") window.__perf.fcp = e.startTime;
  }).observe({ type: "paint", buffered: true });
};

async function measure(browser, seed, throttle) {
  const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
  const cdp = await page.context().newCDPSession(page);
  await cdp.send("Emulation.setCPUThrottlingRate", { rate: throttle });
  await page.addInitScript(INIT);
  await page.goto(`${UPSTREAM_URL}?seed=${seed}`);
  await page.waitForFunction(() => window.__perf.fcp !== undefined, null, { timeout: 60000 });

  const r = await page.evaluate(async (steps) => {
    const nav = performance.getEntriesByType("navigation")[0];
    const svg = document.getElementById("SVG");
    const byTag = {};
    for (const c of MEM.chunks) {
      if (MEM.cursx - MEM.cwid < c.x && c.x < MEM.cursx + MEM.windx + MEM.cwid) {
        byTag[c.tag] = (byTag[c.tag] || 0) + c.canv.length;
      }
    }
    const first = {
      svgInserted: window.__perf.svgInserted,
      fcp: window.__perf.fcp,
      load: nav.loadEventStart,
      elements: svg.querySelectorAll("*").length,
      bytes: MEM.canv.length,
      byTag,
    };
    const frame = () => new Promise((res) => requestAnimationFrame(() => res()));
    const times = [];
    for (let i = 0; i < steps; i++) {
      const t = performance.now();
      xcroll(200);
      await frame();
      times.push(performance.now() - t);
    }
    times.sort((a, b) => a - b);
    first.scrollStep = times[Math.floor(times.length / 2)];
    return first;
  }, SCROLL_STEPS);
  await page.close();
  return r;
}

const median = (xs) => {
  const s = [...xs].sort((a, b) => a - b);
  return s.length % 2 ? s[(s.length - 1) / 2] : (s[s.length / 2 - 1] + s[s.length / 2]) / 2;
};
const ms = (x) => `${Math.round(x)}`;
const mb = (x) => (x / 1e6).toFixed(2);

const browser = await launch();
const results = {};
for (const p of PROFILES) {
  results[p.name] = {};
  for (const seed of SEEDS) {
    results[p.name][seed] = await measure(browser, seed, p.throttle);
    const r = results[p.name][seed];
    console.log(`${p.name.padEnd(26)} ${seed.padEnd(14)} svg ${ms(r.svgInserted)} fcp ${ms(r.fcp)} scroll ${ms(r.scrollStep)} el ${r.elements}`);
  }
}
const chromium = browser.version();
await browser.close();

let md = `# Baseline: upstream {Shan, Shui}*

Generated by \`pnpm perf\` (tools/perf.js) on ${new Date().toISOString().slice(0, 10)}, Chromium ${chromium}, headless, Windows 11 desktop machine.
Later performance budgets are set relative to these numbers. Absolute times depend on the machine; compare runs from the same machine.

Each row is one page load of \`upstream/index.html?seed=S\`, first screen (3000 x 800 SVG). Times in milliseconds from navigation start.

- **svg inserted**: generation of the first screen plus \`innerHTML\`.
- **first paint**: first contentful paint as Chromium reports it. In these runs it came after the load event on desktop but before it under throttling, so treat it as approximate in headless mode; **svg inserted** is the more stable number.
- **scroll step**: median of ${SCROLL_STEPS} \`xcroll(200)\` calls plus the next frame. Upstream rebuilds the whole SVG on every step.
- **elements**: elements inside the on-screen \`<svg>\`. **MB**: size of the on-screen markup.

`;
for (const p of PROFILES) {
  const rows = Object.entries(results[p.name]);
  md += `## ${p.name}\n\n| seed | svg inserted | first paint | load | scroll step | elements | MB |\n|---|---:|---:|---:|---:|---:|---:|\n`;
  for (const [seed, r] of rows) {
    md += `| ${seed} | ${ms(r.svgInserted)} | ${ms(r.fcp)} | ${ms(r.load)} | ${ms(r.scrollStep)} | ${r.elements} | ${mb(r.bytes)} |\n`;
  }
  const col = (k) => median(rows.map(([, r]) => r[k]));
  md += `| **median** | **${ms(col("svgInserted"))}** | **${ms(col("fcp"))}** | **${ms(col("load"))}** | **${ms(col("scrollStep"))}** | **${Math.round(col("elements"))}** | **${mb(col("bytes"))}** |\n\n`;
}
const tags = [...new Set(Object.values(results.desktop).flatMap((r) => Object.keys(r.byTag)))];
md += `## Markup by chunk type (desktop, first screen, MB)\n\nChunks within one chunk width of the window, as \`chunkrender\` selects them. \`mount\` includes each mountain's \`water\` chunk.\n\n| seed | ${tags.join(" | ")} |\n|---|${tags.map(() => "---:").join("|")}|\n`;
for (const [seed, r] of Object.entries(results.desktop)) {
  md += `| ${seed} | ${tags.map((t) => mb(r.byTag[t] || 0)).join(" | ")} |\n`;
}
writeFileSync(new URL("../docs/baseline.md", import.meta.url), md);
console.log("wrote docs/baseline.md");
